require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'umpa8' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase/Analytics'
  pod 'KakaoOpenSDK', '~> 1.21.0'
  pod 'naveridlogin-sdk-ios'

  target 'umpa8Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #
  #use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'umpa8-tvOS' do
  # Pods for umpa8-tvOS

  target 'umpa8-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
